config/routes.rb
Rails.application.routes.draw do
  root to: "backup#index"

  # Volume / backup routes
  get 'volume', to: "backup#index", as: :volume_list
  
  post 'backup/create', to: "backup#create", as: :backup_create
  post 'backup/create/:name/:file', to: "backup#create", as: :backup_quick_create
  
  post 'backup/all', to: "backup#batch_all", as: :backup_all
  post 'backup/selected', to: "backup#batch_selected", as: :backup_selected
  
  delete 'volume/:id', to: "backup#delete", as: :volume_delete
  
  # Restore routes
  get 'restore', to: "recover#index", as: :restore_list
  
  post 'restore/create', to: "recover#create", as: :restore_create
  post 'restore/create/:name/:volume', to: "recover#create", name: /[^\/]+/ , as: :restore_quick_create
  
  post 'restore/all', to: "recover#batch_all", as: :restore_all
  post 'restore/selected', to: "recover#batch_selected", as: :restore_selected
  
  get '/restore/upload', to: 'recover#upload', as: :restore_upload
  post '/restore/upload', to: 'recover#save', as: :restore_save
  
  get '/restore/download/:file', to: 'recover#download', as: :restore_download
  
  delete '/restore/:file', to: 'recover#delete', as: :restore_delete
  
  # Session routes
  get 'authenticate', to: "session#new"
  post 'session/create'
  delete 'session/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task
	include ActiveModel::Model

    # Dinamically create class methods 
    ["backup", "restore"].each do | method |
        define_singleton_method ("get_running_#{method}") { Task.get_running method }
        define_singleton_method ("add_#{method}") { | id | Task.add method, id }
        define_singleton_method ("remove_#{method}") { | id | Task.remove method, id }
    end

    private

    def self.get_running key
        if $redis.get(key).nil?
            return []
        end
        return eval $redis.get(key)
    end

    def self.add key, id
        running = []
        unless $redis.get(key).nil?
            running = eval $redis.get(key)
        end
        running.append(id)
        $redis.set(key, running.to_s)
    end

    def self.remove key, id
        running = eval $redis.get(key)
        running = running - [id]
        $redis.set(key, running.to_s)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_logged_in

    private
    def authenticate!
        if Rails.application.config.password_enabled && !session[:vbt]
            redirect_to authenticate_path
        end
    end

    def set_logged_in
        @logged_in = session[:vbt]
    end
end

app/controllers/backup_controller.rb
class BackupController < ApplicationController
  before_action :authenticate!
  before_action :set_volumes, only: [:index, :batch_all]
  def index
    @running = Task.get_running_backup
  end

  def create
    volume = params[:name]
    file = params[:file]
    process_batch( 
      [ { volume: volume, file: file} ],
      "Backup for volume #{volume} was successfully scheduled. It may take some time to complete.")
    redirect_to volume_list_path
  end

  def batch_all
    process_batch( 
      @volumes.map{ | volume | { volume: volume["Name"] , file: volume["Name"] } },
      "Backups for all volumes were successfully scheduled. It may take some time to complete.")
    redirect_to volume_list_path
  end

  def batch_selected
    process_batch( 
      params[:volumes].map{ | volume_name | { volume: volume_name , file: volume_name } },
      "Backups for selected volumes were successfully scheduled. It may take some time to complete.")
    redirect_to volume_list_path
  end

  def delete
    name = params[:id]
    v = Docker::API::Volume.new
    r = v.remove(name)
    if r.success?
      flash[:success] = "Volume successfully deleted."
    else
      flash[:danger] = r.json["message"]
    end
    redirect_to volume_list_path
  end

  private

  def set_volumes
    volume = Docker::API::Volume.new
    @volumes = volume.list.json["Volumes"].sort { |a, b| a["Name"] <=> b["Name"] }.filter { |v| v["Name"] != "docker-backup" }
  end

  def process_batch list, msg
    list.each do |item|
      VolumeBackupJob.perform_later item[:volume], item[:file]
      Task.add_backup item[:volume]
    end
    flash[:primary] = msg
  end
end

app/controllers/recover_controller.rb
class RecoverController < ApplicationController
  before_action :authenticate!
  before_action :set_files, only: [:index, :batch_all]
  def index
    @running = Task.get_running_restore
  end

  def create
    process_batch(
      [ { file: params[:name] , volume: params[:volume] } ],
      "Volume creation was successfully scheduled. It may take some time to complete.")
    redirect_to restore_list_path
  end

  def batch_all
    process_batch(
      @files.map{ | file | { file: file[:full_name], volume: file[:short_name] } },
      "Volume creation was successfully scheduled. It may take some time to complete.")
    redirect_to restore_list_path
  end

  def batch_selected
    process_batch(
      params[:files].map { |file| { file: "#{file}.tar", volume: file } },
      "Volume creation was successfully scheduled. It may take some time to complete.")
    redirect_to restore_list_path
  end

  def download
    file = params[:file]
    send_file "/backup/#{file}.tar", type: 'application/x-tar', status: 202
  end

  def delete
    file = params[:file]
    File.delete("/backup/#{file}.tar") if File.exist?("/backup/#{file}.tar")
    flash[:success] = "The backup file was successfully deleted."
    redirect_to restore_list_path
  end

  def upload
  end

  def save
    params[:file].each do |uploaded_io| 
      File.open(Rails.root.join('/backup', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end
    end
    redirect_to restore_list_path
  end

  private

  def set_files
    @files = Dir.entries("/backup").select{|el| el != "." && el != ".."}.map{ | f | { full_name: f, short_name: f.split(".")[0] } }
  end

  def process_batch list, msg
    list.each do |item|
      VolumeRecoveryJob.perform_later item[:file], item[:volume]
      Task.add_restore "#{item[:file]}"
    end
    flash[:primary] = msg
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    unless Rails.application.config.password_enabled
      redirect_to root_path
    end
  end

  def create
    password = params[:password]
    if password == Rails.application.config.password
      session[:vbt] = true
    end
    redirect_to root_path
  end

  def destroy
    session[:vbt] = false
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def space
        # prevent haml whitespace being stripped in staging and production
        # which would lead to elements being stuck together.
        # As in development whitespace is not stripped, it looks good in
        # development even without this helper.
        ' '
      end
end

app/helpers/backup_helper.rb
module BackupHelper
end

app/helpers/recover_helper.rb
module RecoverHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/backup/_empty.html.haml
.container.mx-auto.text-center.my-5
    .far.fa-folder-open.h1
    %h2 There is nothing here.
    %p Create a volume from a backup file or using the Docker CLI.

app/views/backup/_volumes.html.haml
= form_with(url: backup_selected_path, method: "post", class: "d-inline") do |f|
  = f.submit "Backup selected", class: "btn btn-sm btn-success"
  = link_to 'Backup all', backup_all_path, method: :post, class: "btn btn-sm btn-success"
  
  .text-center.bg-light
    %p.h4
      %i.fas.fa-cogs
      Running backup tasks:
      %span#running-counter
        = @running.size
  
  %table.table.table-striped
    %thead
      %tr
        %th
          %input(type="checkbox" id="check-all")
        %th Name
        %th Mountpoint
        %th Created at
        %th
        %th
    %tbody
      - @volumes.each do |volume|
        %tr
          %td
            %input{value: volume['Name'], type: "checkbox", name: "volumes[]", class: "form-checkbox"}
          %td= volume["Name"].size > 24 ? "#{volume["Name"][0,21]}..." : volume["Name"]
          %td= volume["Mountpoint"].size > 42 ? "#{volume["Mountpoint"][0,39]}..." : volume["Mountpoint"]
          %td= volume["CreatedAt"]
          %td(class="icon-#{volume['Name']}")
            = @running.include?(volume['Name']) ? '<i class="fas fa-cogs"></i>'.html_safe  : ''
          %td
            = link_to 'Create backup', "#", {class:"btn btn-success btn-sm", 'data-bs-toggle'=>"modal", 'data-bs-target'=>"#modal-#{volume['Name']}"}
            = link_to backup_quick_create_path(volume['Name'],volume['Name']), method: :post, class:"btn btn-success btn-sm", title: "Quick backup", "data-bs-toggle" => "tooltip", "data-bs-placement"=>"top" do
              %i.fas.fa-tachometer-alt 
            = space
            = link_to volume_delete_path(volume["Name"]), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm", title: "Delete volume", "data-bs-toggle" => "tooltip", "data-bs-placement"=>"top" do
              %i.fas.fa-trash-alt 

- @volumes.each do |volume| 
  %div(class="modal fade" id="modal-#{volume['Name']}" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true")
    .modal-dialog
      .modal-content
        .modal-header
          %h5.modal-title#exampleModalLabel Create new backup file
          %button(type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close")
        .modal-body
          = form_with(url: backup_create_path, method: "post") do |form|
            .form-group
              = form.label :name, "Volume name"
              = form.text_field :name, value: volume['Name'], readonly: "readonly", class: "form-control"
            .form-group
              = form.label :file, "Backup file name"
              = form.text_field :file, value: volume['Name'], class: "form-control"
            .mt-3.actions
              = form.submit "Create", class: "btn btn-success form-control"

app/views/backup/index.html.haml
%h1 Docker volumes
%p 
  From this page you can create a 
  %span.badge.bg-primary .tar
  file from any existing volume.
- if @volumes.size > 0
  = render "volumes"
- else
  = render "empty"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Volume Backup Tool
    %meta(name="viewport" content="width=device-width,initial-scale=1")
    = csrf_meta_tags
    = csp_meta_tag
    %link(href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous")
    %link(rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer")
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('favicon.png')
  
  %body
    %nav.navbar.navbar-dark.bg-dark
      %ul.nav.justify-content-end
        %li.nav-item
          = link_to "Volumes", volume_list_path, class: "nav-link link-light"
        %li.nav-item
          = link_to "Restore", restore_list_path, class: "nav-link link-light"

        - if @logged_in
          %li.nav-item
            = link_to "Log out", session_destroy_path, method: :delete,class: "nav-link link-light"

    .container
      = yield
    
    
    .toast-container.position-fixed.bottom-0.end-0.p-3#toast-container
      - flash.each do |key, value|
        %div(class="toast" role="alert" aria-live="assertive" aria-atomic="true")
          %div(class="toast-header bg-#{key} text-white")
            %strong.me-auto Notification
            %small.text-muted
            %button(type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close")
          .toast-body
            = value

    %script(src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous")
    = javascript_pack_tag 'custom'

app/views/recover/_backups.html.haml
= form_with(url: restore_selected_path, method: "post", class: "d-inline") do |f|
  = f.submit "Recover selected", class: "btn btn-sm btn-success"
  = link_to 'Recover all', restore_all_path, method: :post, class: "btn btn-sm btn-success"

  .text-center.bg-light
    %p.h4
      %i.fas.fa-cogs
      Running restore tasks: 
      %span#running-counter
        = @running.size

  %table.table.table-striped
    %thead
      %tr
        %th
          %input(type="checkbox" id="check-all")
        %th Name
        %th
        %th
    %tbody
      - @files.each do |file|
        %tr
          %td
            %input(value="#{file[:short_name]}" type="checkbox" name="files[]" class="form-checkbox")
          %td= file[:full_name].size > 24 ? "#{file[:full_name][0,21]}..." : file[:full_name]
          %td(class="icon-#{file[:full_name]}")
            = @running.include?(file[:full_name]) ? '<i class="fas fa-cogs"></i>'.html_safe  : ''
          %td
            = link_to "Create volume", "#", {class:"btn btn-success btn-sm", 'data-bs-toggle'=>"modal", 'data-bs-target'=>"#modal-#{file[:short_name]}"}
            
            = link_to restore_quick_create_path(file[:full_name], file[:short_name]), method: :post, class:"btn btn-success btn-sm", title: "Quick restore", "data-bs-toggle" => "tooltip", "data-bs-placement"=>"top" do
              %i.fas.fa-tachometer-alt
            = space
            = link_to restore_download_path(file[:full_name]), target: "_blank", class:"btn btn-primary btn-sm", title: "Download file", "data-bs-toggle" => "tooltip", "data-bs-placement"=>"top" do
              %i.fas.fa-download
            = space
            = link_to restore_delete_path(file[:short_name]), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm", title: "Delete file", "data-bs-toggle" => "tooltip", "data-bs-placement"=>"top" do
              %i.fas.fa-trash-alt

- @files.each do |file|
  %div(class="modal fade" id="modal-#{file[:short_name]}" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true")
    .modal-dialog
      .modal-content
        .modal-header
          %h5.modal-title#exampleModalLabel Create new volume
          %button(type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close")
        .modal-body
          = form_with(url: restore_create_path, method: "post", local: true) do |form| 
            .form-group
              = form.label :name, "File name"
              = form.text_field :name, value: file[:full_name], readonly: "readonly", class: "form-control"
            .form-group
              = form.label :volume, "New volume name"
              = form.text_field :volume, value: file[:short_name], class: "form-control"
            .mt-3.actions
              = form.submit "Create", class: "btn btn-success form-control"

app/views/recover/_empty.html.haml
.container.mx-auto.text-center.my-5
    %i.far.fa-folder-open.h1
    %h2 There is nothing here.
    %p Create a backup from a volume or upload a file.

app/views/recover/index.html.haml
%h1 Restore files
%p 
  From this page you can create a volume from any 
  %span.badge.bg-primary .tar
  file listed below.</p>

= link_to restore_upload_path, class:"btn btn-primary btn-sm" do
  %i.fas.fa-upload
  Upload file
= space

- if @files.size > 0 
  = render 'backups'
- else
  = render 'empty'

app/views/recover/upload.html.haml
%h1 Recovery files
%p 
    Upload 
    %span.badge.bg-primary .tar
    file.

.col-8.m-auto
    = form_with(url: restore_save_path, method: "post") do |form|
        .form-group
            = form.label :file, "Select file"
            = form.file_field :file, multiple: true, accept: "application/x-tar"
        .mt-3.actions
            = form.submit "Upload file", class: "btn btn-primary form-control"

app/views/session/new.html.haml
%h1 Authenticate

.col-8.m-auto
    = form_with(url: session_create_path, method: "post", local: false) do |form|
        .form-group
            = form.password_field :password, placeholder: "Password" ,class: "form-control"
        .mt-3.actions
            = form.submit "Authenticate", class: "btn btn-primary form-control"